services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: "on-failure"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "80:80"
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/app/public
      - ./data/nginx_cache:/tmp/nginx_cache
    depends_on:
      - api
      - localstack

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    # volumes:
    #   - "localstack-data:/tmp/localstack/data"

  # sqs-ui:
  #   image: softwaremill/elasticmq-native
  #   ports:
  #     - "9324:9324"

  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./data:/app/data
      - ./public:/app/public
    depends_on:
      - localstack
      # - ollama
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=tes_

  generate-recommendations:
    container_name: generate-recommendations
    build:
      context: .
      dockerfile: Dockerfile.python
    command: ["python", "app.py"]
    env_file:
      - .env
    volumes:
      - ./recommendation-app:/app
      - ./data:/app/data

  calculate-rfv:
    container_name: calculate-rfv
    image: golang:tip-alpine3.21
    working_dir: /go/src
    # command: ["tail", "-f", "/dev/null"]
    command: ["go", "run", "app.go"]
    env_file:
      - .env
    volumes:
      - ./calculate-rfv-app:/go/src

  # ollama:
  #   image: ollama/ollama
  #   entrypoint: ["/bin/sh", "-c"]
  #   command: ["ollama serve & sleep 5 && ollama run llama3.2 && wait"]
  #   # command: ["ollama", "run", "llama3"]
  #   # entrypoint: ["/bin/sh", "-c", "ollama run llama3"]
  #   ports:
  #     - 11434:11434

volumes:
  localstack-data:
